// <auto-generated />
namespace RaceTrackMVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class temp21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(temp21));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270326209_temp21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
